optionz=(
  APPEND_HISTORY
  AUTO_CD
  CD_ABLE_VARS
  CORRECT
  EXTENDED_GLOB
  EXTENDED_HISTORY
  HIST_EXPIRE_DUPS_FIRST
  HIST_FIND_NO_DUPS
  HIST_IGNORE_ALL_DUPS
  HIST_IGNORE_DUPS
  HIST_IGNORE_SPACE
  HIST_NO_FUNCTIONS
  HIST_NO_STORE
  HIST_REDUCE_BLANKS
  HIST_SAVE_NO_DUPS
  HIST_VERIFY
  KSH_OPTION_PRINT
  INC_APPEND_HISTORY
  INTERACTIVE_COMMENTS
  NO_BAD_PATTERN
  NO_BEEP
  NO_HIST_BEEP
  NO_MATCH
  SHARE_HISTORY
)

for zoption in ${optionz[@]}
  do
    setopt $zoption
done
