theme = "onedark"

[editor]
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.search]
wrap-around = false

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "spacer"]
right = ["diagnostics", "selections", "position-percentage", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"

