theme = "gruvbox"

[editor]
rulers = [80]
scrolloff = 5
color-modes = true
cursorline = true
line-number = "relative"
true-color = true
auto-format = false

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics"]
center = ["file-name", "spacer"]
right = ["file-type", "position-percentage", "position"]
